// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArrangeWindows(arg1, arg2) {
  return window['go']['main']['App']['ArrangeWindows'](arg1, arg2);
}

export function ClearToken() {
  return window['go']['main']['App']['ClearToken']();
}

export function CreateProfile() {
  return window['go']['main']['App']['CreateProfile']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function ImportProfile(arg1, arg2) {
  return window['go']['main']['App']['ImportProfile'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ScanTokens() {
  return window['go']['main']['App']['ScanTokens']();
}

export function SelectToken(arg1) {
  return window['go']['main']['App']['SelectToken'](arg1);
}

export function StartProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProfile'](arg1, arg2, arg3);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function UpdateFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2);
}
